Fix handling app_path

diff --git a/rails-new b/rails-new
--- a/rails-new
+++ b/rails-new
@@ -1,17 +1,5 @@
 #!/bin/bash
 
-execute() {
-  echo -n $'\e[35m'
-  echo -n $ "$@"
-  echo    $'\e[0m'
-  "$@"
-  if [ $? -ne 0 ]; then
-    echo 'Error occurred' >&2
-    exit 2
-  fi
-}
-
-
 if [ $# -eq 0 ]; then
   echo './rails-new APP_PATH [options]' >&2
   exit 1
@@ -20,20 +8,20 @@ fi
 app_path="$1"
 shift
 
-app_name="${app_path##*/}"
-rails_new_root="$(dirname $0)"
-tmp_app_path="$rails_new_root/$app_name"
-if [ -e "$tmp_app_path" ]; then
-  execute rm -rf "$tmp_app_path"
+if [ -e "$app_path" ]; then
+  echo "$app_path already exists" >&2
+  exit 2
 fi
 
-cd "$rails_new_root"
-execute bundle exec rails new "$app_name" -m template.rb --skip-bundle -T "$@"
-cd -
-
-if [ "$tmp_app_path" != "$app_path" ]; then
-  if [ -e "$app_path" ]; then
-    execute rm -rf "$app_path"
-  fi
-  execute mv "$tmp_app_path" "$app_path"
+mkdir "$app_path"
+absolute_path="$(cd "$app_path" >/dev/null 2>&1 && pwd)"
+rmdir "$app_path"
+if [ -z "$absolute_path" ]; then
+  echo "cannot get absoulte app_path" >&2
+  exit 3
 fi
+
+cd "$(dirname $0)"
+echo $ \
+bundle exec rails new "$absolute_path" -m template.rb --skip-bundle -T "$@"
+bundle exec rails new "$absolute_path" -m template.rb --skip-bundle -T "$@"
